### ISSUE TITLE
MongoAuth assumes username

### ISSUE THREAD

**Issue by DieterDePaepe** [eclipse-vertx/vertx-auth#87] opened 2016-09-26 21:42 UTC
### Version
- vert.x core: 3.3.3
- vert.x auth: 3.3.3
### Context

I noticed the MongoAuth is assuming that users are identified using a username. This applies to both the API (eg from `MongoAuthImpl`: `public void insertUser(String username, String password,...)`), as well as any error messages: (eg: `resultHandler.handle((Future.failedFuture("Username must be set for authentication.")));`).

I would like to use user emails rather than usernames, and although I perfectly can using the customisation options, I do feel there is a bit of a mismatch.

I suggest replacing username by userIdentifier or something similar. This could be changed without breaking compatibility.

**Comment by pmlopes** [comment] 2016-09-29 11:45
`username` is just the name of the property you can store email addressed there.

**Comment by DieterDePaepe** [comment] 2016-09-29 12:04
I know it works like that. But getting an error "Username must be set..." will lead to confusion for people not familiar with that detail. Using a neutral name in variables and errors looks like an easy improvement.

**Comment by pmlopes** [comment] 2016-09-29 12:08
Ok, so the issue is the error message then.

**Comment by DieterDePaepe** [comment] 2016-09-29 12:13
3 things actually:
- error messages (changing is backwards compatible)
- parameter names, as these should also show the intent (backwards compatible)
- the constants in MongoAuth, such as `PROPERTY_USERNAME_FIELD` (not backwards compatible, but current ones could be deprecated till next major revision)

**Comment by pmlopes** [comment] 2023-01-30 15:15
The mongo auth has been kept back at the old location, so we're closing this issue as it is not included here.

**Closed as completed by pmlopes** 2023-01-30 15:15 UTC
Labels: enhancement, wishlist
