### ISSUE TITLE
Oauth2 provider is throwing exception when token is decoded

### ISSUE THREAD

**Issue by julienBaleizao** [eclipse-vertx/vertx-auth#195] opened 2018-03-06 10:38 UTC
### Version

* vert.x core:3.5.1
* vert.x auth:3.5.1
* vertx-web:3.5.1

### Context

I want to secure my API with Oauth providers. For this purpose I am using the Vertx implementation for Facebook, GitHub ...
I am using the AUTH_CODE flow to retrieve my token. I get a RuntimeException when the Oauth2TokenImpl tries to decode the token as a JWT token. I have seen that in the master branch this exception is logged as DEBUG instead of WARN.
What I understand here is that this exception is normal of the basic oauth2 flow not using JWT token.
Can you confirm this ? When do you have planned to make the next release which will include the log level change ?

### Do you have a reproducer?

Implement the FacebookAuth provider provided by Vertx.

### Steps to reproduce

1. Get an authentification code from Facebook
2. use the following method:
```
authGithubProvider.authenticate(new JsonObject().put("code", code.get(0)).put("redirect_uri", "http://localhost:8080/oauth2/callback"), res -> {
                    OAuth2TokenImpl oAuth2Token = (OAuth2TokenImpl) res.result();
                    if (res.failed()) {
                        System.out.println("Get the token failed: " + res.toString());
                    } else {
                        System.out.println("Token retrieved: " + oAuth2Token.opaqueAccessToken() + ";" + oAuth2Token.opaqueRefreshToken());
                    }
                });
```
3. Check the server log to see the stack trace for token decoding.

**Comment by pmlopes** [comment] 2018-03-06 12:43
Duplicate of: https://github.com/vert-x3/vertx-auth/pull/186

The log is just noise at the moment, the exception is handled internally.

**Closed as completed** 2018-03-06 12:44 UTC
Labels: duplicate
