### ISSUE TITLE
Vertx Auth JWT - Chaining providers

### ISSUE THREAD

**Issue by lusoalex** [eclipse-vertx/vertx-auth#483] opened 2021-05-19 22:06 UTC
### Describe the feature

I need to chain two JWT authentication providers, so I followed this documentation: https://vertx.io/docs/vertx-auth-common/java/#_chaining_authentication_providers

#### Step one: Create first JWTAuth

The first AuthProvider is a JwtAuth created through io.vertx.ext.auth.jwt.JWTAuth.create resulting in a `JWTAuthProviderImpl` object.

#### Step two: Create the second JWTAuth

The second one is a custom JWTAuth (named JWTClaimsVerifier), which basically, adds some extra check on claims in addition to what is already done by the previous JWTAuth (exp, nbf, etc...). 
_Ex: ensure there is no `ati` claims (some authorization servers use JWT as refresh token instead of opaque tokens, so they add an **_ati_** `access token identifier` claim referring to the "true" access_token identifier, aka `jti` that has been generated in the same time). As a result, the difference between refresh and access Json Web Token is the presence of the `ati` claim on refresh._ In my case, the custom JWTAuth will reject such refresh tokens. _There are some others claims property checks specific to our company business case, not relevant for this request._

#### Step three: Chain the authentication providers

Here I followed the documentation mentioned above by using: ChainAuth.all() and adding the two JWTAuth, resulting in a ChainAuth authentication provider.

#### Last step: Creating an Authentication Handler.

I can't use the JwtAuthHandler as it expects a JWTAuth to create a JWTAuthHandlerImpl and I have now a ChainAuth.

I wanted to create my own handler `JWTChainAuthHandlerImpl` like this
```JAVA
 JWTChainAuthHandlerImpl extends HTTPAuthorizationHandler<ChainAuth> 
```
but the HTTPAuthorizationHandler is not public.

I do not want to duplicate the code of the HTTPAuthorizationHandler, extracting token from an Authorization header is something basic, so I was wondering if : 

 - it would be possible to make HTTPAuthorizationHandler public
 - or it would be possible to add a JWTChainAuthHandler into the Vertx library?

### Contribution

For both suggestions or any other from your part, I am willing to contribute.

### How do I manage this currently...

I have created a custom chain authentication like this : 
```JAVA
public class JWTChainAuthProvider implements ChainAuth, JWTAuth {
```
This way I can use the `io.vertx.ext.web.handler.JWTAuthHandler.class` but it is a kind of copy/paste of the `io.vertx.ext.auth.impl.ChainAuthImpl` with as differences: 

 - The vertx ChainAuth method "call order" is: authenticate(Credentials cred, Handler res) -> authenticate(JsonObject auth, Handler res)
 - On my side: authenticate(JsonObject auth, Handler res) -> authenticate(Credentials cre, Handler res)

I did this because the `io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl` has not the same "calling order".
I do not know if this different call order is something "normal"?

Thanks in advance for getting time to read this.
Alexandre.

**Comment by pmlopes** [comment] 2021-05-20 15:41
@lusoalex I think there are a couple of things we need to improve here. Perhaps we need to relax the strictness of the provider in the handler.

Second, several refactorings have taken place in master and will be available in 4.1.0.CR1 which allows creating custom auth handlers should be easier using class composition instead of inheritance. See if https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/SimpleAuthenticationHandler.java is enough for you?

I've also to say that several bugs related to chain processing have been fixed too in CR1...

**Comment by lusoalex** [comment] 2021-05-21 12:26
@pmlopes I do agree to be less strict. thanks I'll create a branch to test the coming 4.1.0 changes and come back to you with my feedbacks.

**Comment by lusoalex** [comment] 2021-05-24 15:52
Hi @pmlopes as promised, here's the first feedback.

 - I first migrated from 4.0.2 to 4.0.3, and resolve the breaking changes thanks to this [note](https://github.com/vert-x3/wiki/wiki/4.0.3-Deprecations-and-breaking-changes#vertx-auth). 👍🏼
 - I then migrated to 4.1.0.CR1 and had to solve a missing class, `io.vertx.ext.web.handler.impl.HttpStatusException` that has been renamed and moved to `io.vertx.ext.web.handler.HttpException`, it should be part of the [breaking change note](https://github.com/vert-x3/wiki/wiki/4.1.0-Deprecations-and-breaking-changes), do you agree? _Nothing complicated anyway..._

Unfortunately, I still blocked for now due to a problem coming from `JWTAuthHandlerImpl.postAuthentication`, and more precisely due to an `IllegalStateException("Invalid JWT: null")` [here](https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java#L119)
```JAVA
    // the user is authenticated, however the user may not have all the required scopes
    if (scopes.size() > 0) {
      final JsonObject jwt = ctx.user().get("accessToken");
      if (jwt == null) {
        ctx.fail(403, new IllegalStateException("Invalid JWT: null"));
        return;
      }
```
The access token is not in the user context anymore`ctx.user().get("accessToken");`
**_Furthermore we should use a HttpException, on my side it ends up with a 500 status code instead of the 403..._**

I read the release note and saw the [right way to specify scopes](https://github.com/vert-x3/wiki/wiki/4.1.0-Deprecations-and-breaking-changes#vertx-auth).

As scopes are now part of the auth provider, the code related to scopes management present into `JWTAuthHandlerImpl` should rely on the auth provider instead of being performed within the handler, right?

FYI, these scopes are automatically injected from the openapi module [here](https://github.com/vert-x3/vertx-web/blob/master/vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/AuthenticationHandlersStore.java#L71)
```JAVA
// this mutates the state, so we replace the list with an updated handler
AuthenticationHandler updatedHandler = scopedHandler.withScopes(scopes);
```

And this part is linked with another discussion I tried to open [here](https://groups.google.com/g/vertx/c/0aNjOLrgUlo/m/lvuc1DT8BQAJ). 
_Should I open an issue instead?_

From my point of view, the method `JWTAuthHandlerImpl.withScopes(...)` is a good thing regarding open API specifications. Because as explained in the google group, each endpoint may have a different scope list, because exposing different resources or without the same access conditions. While the JWTHandler should be the same (same issuer, signature key, ...), we should be able to "override" the scopes list...

I'll wait for your comments before going further, thanks again for your time!

**Comment by lusoalex** [comment] 2021-05-25 16:27
Hi @pmlopes to complete my previous comment, I think the key point is to see how do we manage  `ScopedAuthentication<SELF extends AuthenticationHandler>` which introduces `withScopes` methods.
I believe we need it (this is useful and needed by the openapi spec), and need to find out how to properly handle them in Vert.X 4.1.x release.

In addition to that, I would like to discuss with you how scopes are checked. The default behavior act as a "allOf", I mean the scope list defined in the openapi spec must all be included into the JWT. I would like to introduce a "anyOf" and keep as default behavior the "allOf". (Something similar to what have be done in the ChainAuth).
The reason is, for one endpoint, I may require any scope among ("profile", "email", "gender") and say "ok" if the JWT owns at least one of them.

See you,
Alexandre.

**Comment by pmlopes** [comment] 2021-05-26 13:33
> I then migrated to 4.1.0.CR1 and had to solve a missing class, io.vertx.ext.web.handler.impl.HttpStatusException that has been renamed and moved to io.vertx.ext.web.handler.HttpException, it should be part of the breaking change note, do you agree? Nothing complicated anyway...

Good catch! Done!

**Comment by ikstewa** [comment] 2021-06-29 01:00
@lusoalex Have you tried chaining the security auth handlers to get 'anyOf' support for scopes? I'm not certain if this is valid for OpenAPI to duplicate the security handler, but I think it should work for Vertx.

All scopes:
```
security:
   - OAuth2: [scope1, scope2]
```
Any scope:
```
security:
   - OAuth2: [scope1]
   - OAuth2: [scope2]
```

**Comment by pmlopes** [comment] 2021-09-15 13:34
@lusoalex I've merged your original PR + some updates as we were discussing in order to get this for 4.2.0. I'll close this issue for now as many improvements have been already been done in web and auth. Feel free to reopen if the issue isn't still fixed.

**Closed as completed by pmlopes** 2021-09-15 13:34 UTC
Labels: enhancement
