### ISSUE TITLE
Vertx Shiro's BasicAuthentication fail when login with browser

### ISSUE THREAD

**Issue by dangnhdev** [eclipse-vertx/vertx-auth#75] opened 2016-07-11 01:09 UTC
### Version
- vert.x core: 3.3.0
- vert.x auth: 3.3.0
### Context

I written some code to perform Basic Authentication with Vertx ShiroAuth.

``` java
    JsonObject authConfigObject = new JsonObject();
        authConfigObject.put(
                PropertiesProviderConstants.PROPERTIES_PROPS_PATH_FIELD,
                new File(appConfig.getUserPropertiesPath()).toURI().toString() /*to let shiro auto reload properties file */
        );

        ShiroAuthOptions shiroAuthOptions = new ShiroAuthOptions();
        shiroAuthOptions.setType(ShiroAuthRealmType.PROPERTIES);
        shiroAuthOptions.setConfig(authConfigObject);
```

Example properties file:

```
user.admin=12345678
user.staff=123
```

When user login with browser, vertx throw a null Throwable ([stacktrace](https://gist.github.com/dangxunb/1cb9a08730b9b7717fab6f31e9fd51b1)), hence we must add this stupid if block to handle it:

``` java
    public void handleFailure(RoutingContext context) {
        if (context.failure() == null || context.failure() instanceof FileNotFoundException) {
            context.next();
            return;
        }
   //handle another failure....
```

I feel that add that if block is a trick :(

**Comment by pmlopes** [comment] 2016-09-16 08:30
@dangxunb can you provide a full reproducer? I've tried to use your code in a test and i cannot seem to get the null pointer exception, could it be that it comes from the line:

``` java
new File(appConfig.getUserPropertiesPath()).toURI().toString()
```

**Comment by pmlopes** [comment] 2018-04-09 08:12
Its been more than 1 year waiting for feedback. Since the issue could not be reproduced, i'll close it.

**Closed as completed by pmlopes** 2018-04-09 08:12 UTC
Labels: invalid
