### ISSUE TITLE
JWTAuth - Manage keys rotation

### ISSUE THREAD

**Issue by impolitepanda** [eclipse-vertx/vertx-auth#285] opened 2019-06-27 13:53 UTC
### Version

* vert.x core: 3.7.1
* vert.x auth: 3.7.1

### Context

Hello! 
I have a need where my JWT keypair have to be replaced at regular time intervals. The problem here is that requires a restart of all my verticles as it seemes like there is no way to dynamically change it at runtime.

### Do you have a reproducer?

* No reproducer

### Extra

* This enhancement was created following this topic on the user group: https://groups.google.com/forum/#!topic/vertx/9wEDRXOL4LA

**Comment by arnauddegiuli** [comment] 2019-09-19 09:29
Sounds like a duplicate of: https://github.com/vert-x3/vertx-auth/issues/282#issue-454760508

**Comment by arnauddegiuli** [comment] 2019-09-19 12:46
Find below a patch that I have done to make me able to refresh keys (I have override class in my project)... I haven't manage jwks case since I m not sure the patch is good enough... 

Arnaud

[JWTAuthManageKeysrotation.zip](https://github.com/vert-x3/vertx-auth/files/3631472/JWTAuthManageKeysrotation.zip)

**Comment by pmlopes** [comment] 2020-07-30 19:12
JWKs and rotation is now fully handled on `oauth2` module which can also handle JWTs

**Closed as completed by pmlopes** 2020-07-30 19:12 UTC
